### ISSUE TITLE
MuJoCo breaking change

### ISSUE THREAD

**Issue by vaxenburg** [NeLy-EPFL/flygym#111]
Looks like the fly model is not compatible with MuJoCo 3.0.0 and above because of a breaking change:

> 11. Removed mjOption.collision and the associated option/collision attribute.

See the changelog [here](https://github.com/google-deepmind/mujoco/releases/tag/3.0.0).

**Comment by sibocw** [comment]
Hi Roman, yes I'm aware of this but haven't had the chance to address it.

I tried following the MuJoCo migration instruction in November or so but ran into an issue with the MuJoCo 3.0.0 release note, and I just put it aside for the time being. I've just opened an issue for this on the MuJoCo repo ([here](https://github.com/google-deepmind/mujoco/issues/1367)). Perhaps you know the solution to this already?

**Comment by vaxenburg** [comment]
Looks like you got the answer already:) Also, related, trying to load the fly XML file in the MuJoCo viewer crashes the viewer for me. I run MuJoCo 3.1.1 on a Mac. I'm wondering if it works for you?

**Comment by sibocw** [comment]
Yes I'll try migrating to 3.x.x next week!

I haven't tried loading it to the viewer yet but it's also on our horizon (though not immediately) to get it working with the MuJoCo interactive viewer.

**Comment by stepanove** [comment]
Hi everyone, the migration instruction was updated/fixed regarding this option recently:
https://github.com/google-deepmind/mujoco/commit/669ee0ee4845b235852f247a1a6806c979129142

Since "contype" and "conaffinity" are set explicitly for all "geom" items, it should be sufficient to just remove  collision="predefined" from XML file.

**Comment by sibocw** [comment]
Fixed in #112
