### ISSUE TITLE
Remove randomness in visual renderinng

### ISSUE THREAD

**Issue by sibocw** [NeLy-EPFL/flygym#116]
I think it's a good idea to either
- remove the composite texture (is this how it's called?) in some body parts, especially legs, or
- find out how to set MuJoCo's random seed for generating these textures

They make the rendering results and vision-related things just _slightly_ different. In visual navigation tasks this makes the whole behavior stochastic (because the slightly different visual input leads to slightly different descending drive and the difference just accumulates).

What do you think? @stimpfli

**Comment by stepanove** [comment]
Actually, the procedural textures should be the same, it looks like mujoco uses a fixed seed already.

> MuJoCo simulations are deterministic with one exception: sensor noise can be generated when this feature is enabled.
> This is done by calling the C function rand() internally. To generate the same random number sequence, call srand()
> with a desired seed after the model is loaded and before the simulation starts. The model compiler calls srand(123)
> internally, so as to generate random dots for procedural textures. Therefore the noise sequence in the sensor data
> will change if the specification of procedural textures changes, and the user does not call srand() after model
> compilation.

https://github.com/search?q=repo%3Agoogle-deepmind%2Fmujoco%20srand(123)&type=code

**Comment by sibocw** [comment]
Thank you! Hmmm then there must be another source of non-determinism somehow, probably just in the rendering since it only impacts vision-related tasks 🤔

I need to dig into this. Thanks for the pointer @stepanove !

**Comment by stepanove** [comment]
No problem. It should be easy to verify by adjusting config.yaml or by changing "mark" to "none" in the code:
https://github.com/NeLy-EPFL/flygym/blob/9425bd152e38b3cbbc5f14a28037de537f11e59b/flygym/mujoco/core.py#L640

**Comment by sibocw** [comment]
Perfect. My next idea is to disable `warmstart` in the compiler options. I will look into this!

**Comment by stepanove** [comment]
@sibocw, I tinkered with vision.py a bit, it looks like the problem is not related to vision, it's in the turning controller. I created a PR draft, but you need to take a closer look at this part, I think.

**Comment by sibocw** [comment]
I see, so it's related to calling check_env! I will look into this later, thanks!

**Comment by stepanove** [comment]
You're welcome!
In this case check_env actually reveals a hidden bug. I added prints to VisualTaxis.reset and VisualTaxis.step, here is what it looks like:
```
check_env begin
reset, seed None
reset, seed 123
reset, seed 123
reset, seed 456
reset, seed None
reset, seed None
step
check_env end
simulation begin
reset, seed 555
step
step
step
.....
```
The reset called on simulation begin (with seed==555) doesn't not clear internal state of CPG network so it keeps some random state from the step done during check_env. At least CPGNetwork.intrinsic_amps is updated in HybridTurningNMF.step and then used in CPGNetwork.reset.
