### ISSUE TITLE
Find a better way to convert notebooks to tutorial pages

### ISSUE THREAD

**Issue by sibocw** [NeLy-EPFL/flygym#122]
I've been using jupyter nbconvert to convert the demo notebooks to RST files for the website. This works OK but some manual finetuning of the RST files are required:
1. Video outputs are not embedded into the notebooks (otherwise they easily get way to large). I'm uploading the output media (videos, large images) to [a separate repo](https://github.com/nely-epfl/_media) so as not to clog this package, and adding them to the RST pages by linking to the "raw" URLs of these files on the separate repo. This needs to be done manually.
2. Sometimes image sizes need to be adjusted so that they display nicely on the website.
3. I added language specifiers to the code blocks to ensure proper Python syntax highlighting.
4. Something else? It's very human-in-the-loop...

This is quite annoying. Maybe we can automate this somehow? How about jupyter book? This is low priority but let's leave this issue here.

**Comment by stepanove** [comment]
Maybe it makes sense to make the tutorials available in colab, just like MuJoCo does? It lowers the entry barrier significantly.

https://mujoco.readthedocs.io/en/latest/python.html#tutorial-notebook

**Comment by sibocw** [comment]
We tried Colab last year when using a primitive version of this package for a course. We moved away from it because
1. When using dm_control, running multiple simulations (even sequentially) caused the Colab runtime to crash due to some threading issue with the EGL renderer. We haven't encountered this problem on any other environment.
3. We wanted the web page to be fully viewable (including videos) without the user having to run the code.
4. It was very slow to run things on Colab that month for some reason (GPUs were scarce maybe?). I don't remember what happened exactly.

Regarding 1, I just tried it again and encountered the same issue. [This notebook](https://github.com/NeLy-EPFL/flygym/files/14280172/cpg_controller.ipynb.txt) crashes the Colab runtime at the last cell. The following is the error stack:
```
Exception ignored in: <function MjrContext.__del__ at 0x7a65e2238e50>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dm_control/mujoco/wrapper/core.py", line 638, in __del__
  File "/usr/local/lib/python3.10/dist-packages/dm_control/mujoco/wrapper/core.py", line 629, in free
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
  File "/usr/local/lib/python3.10/dist-packages/dm_control/_render/base.py", line 135, in make_current
RuntimeError: Cannot make context <dm_control._render.pyopengl.egl_renderer.EGLContext object at 0x7a65da5c9f00> current on thread <Thread(_colab_inspector_thread, started daemon 134578698184256)>: this context is already current on another thread <_MainThread(MainThread, started 134579582074880)>.
```
This only happens on the second simulation of the same notebook and only on Colab. It seem related to a "known issue with dm control" according to [this issue](https://github.com/google-research/pisac/issues/3), but the solution proposed there didn't seem immediately applicable to Colab.

So in the end we decided that it was not worth the effort, as we had a tight timeline for the course. Getting this to work could also be pretty nice.

**Comment by sibocw** [comment]
@stepanove Thank you! Did you encounter this issue before? Was it also with Golab?

**Comment by stepanove** [comment]
Nope, I meant that I wanted to get more familiar with Jupiter/Colab in general, I'm a C++ developer in a normal life :)

**Comment by stepanove** [comment]
@sibocw, it looks like this exception doesn't really break anything (it says it's ignored). I had it few times but the video was generated anyway.
Here is my test [notebok.](https://colab.research.google.com/drive/1sZOXBz0qiFAT94BRVaL6s4WbnmjDj0w7?usp=sharing) It renders raw frames to ensure it doesn't show the video from previous run.


![Снимок экрана от 2024-02-14 20-41-35](https://github.com/NeLy-EPFL/flygym/assets/43698390/bc5f9dc2-31b5-4dc3-80ef-e38556d533d7)

**Comment by stepanove** [comment]
IMHO, an interactive tutorial is way better than just a web page. If I'm not involved into the process I just scroll it paying attention to videos only :)

btw, the size of the notebook with videos is just 5MB.

**Comment by sibocw** [comment]
Hi @stepanove 

> it looks like this exception doesn't really break anything (it says it's ignored). I had it few times but the video was generated anyway.

Interesting! For me it certainly crashed the simulation because the whole Jupyter runtime crashed. I will try to look into this more.

> IMHO, an interactive tutorial is way better than just a web page. If I'm not involved into the process I just scroll it paying attention to videos only :)

I totally agree. If Colab works we can at least provide a link to play with the tutorials on Colab (in any case, the notebook can be opened on Colab simply with the URL `https://colab.research.google.com/github/xxx/xxx/xxx.ipynb`. Our notebooks are already on Github so this should be easy).

> btw, the size of the notebook with videos is just 5MB.

My concern is that the videos might be updated and I don't want another 5MB of data to be tracked by Git every time the notebook changes. This is especially important because the package might be installed/cloned in ephemeral environments (Github Actions, or even Colab notebooks where the package needs to be reinstalled for every runtime).

**Comment by stepanove** [comment]
> My concern is that the videos might be updated and I don't want another 5MB of data to be tracked by Git every time the notebook changes. This is especially important because the package might be installed/cloned in ephemeral environments (Github Actions, or even Colab notebooks where the package needs to be reinstalled for every runtime).

Yep, I also think that storing videos in git (at least in the main package repo) is not good.
I heard github was going to add GPU enabled CI runners, then it can be used to execute notebooks and deploy the results somewhere.
