### ISSUE TITLE
Fly-to-fly tracking: leading fly sinks underground

### ISSUE THREAD

**Issue by sibocw** [NeLy-EPFL/flygym#148]
Problem the leading fly disappears under the floor after a while?? This is in the context of #147.

Video: https://github.com/NeLy-EPFL/flygym/assets/23410765/2320eac9-1bd1-4d9b-ad08-c3df03ecfa79
(The following fly starts from the wrong side of the arena in this example, but you can see the leading fly disappearing anyway.)

To reproduce:
```bash
git checkout fly-following-circle
git pull

# Establish baseline visual system activities
# Note: i'm running this in parallel, but doing so will lead to GPU out-of-memory error.
# Therefore I disabled the GPU by setting CUDA_VISIBLE_DEVICES to "".
CUDA_VISIBLE_DEVICES="" python flygym/examples/vision_connectome_model/response_to_fly.py

# Run closed-loop tracking script
python python flygym/examples/vision_connectome_model/follow_fly_closed_loop.py
```

Notes on `follow_fly_closed_loop.py`:
- It might be helpful to shorten the simulation, but you don't really see the problem unless it's 3s or longer
- Replace the last line (`process_trial("blocks", True, (-5, -10))`) with the line before that's commented out (`Parallel(n_jobs=8)(delayed(process_trial)(*config) for config in configs)`) to run multiple simulations in parallel. On my machine (126GB RAM), 8 processes was as high as I could reach before OOM. Set `CUDA_VISIBLE_DEVICES` too.
- If you don't want to run `response_to_fly.py` which establishes baseline activities of visual system neurons, you can download them here, decompress, and copy them under `outputs/connectome_constrained_vision/baseline_response/`:
[response_stats.zip](https://github.com/NeLy-EPFL/flygym/files/15065595/response_stats.zip)

Feel free to work on `fly-following-circle` directly.

**Comment by tkclam** [comment]
Adding `physics.bind(self.freejoint).qvel[:] = 0` to  the `step` method of `MovingFlyArena` in `flygym/flygym/examples/vision_connectome_model/arena.py` should fix the issue
