### ISSUE TITLE
Format of `.step()`'s return values

### ISSUE THREAD

**Issue by sibocw** [NeLy-EPFL/flygym#15]
Gym actually specifies the format of `.step()`'s return values more strictly than I thought: https://gymnasium.farama.org/api/env/#gymnasium.Env.step

Namely it requires the following:
> - observation (ObsType) – An element of the environment’s [observation_space](https://gymnasium.farama.org/api/vector/#observation_space) as the next observation due to the agent actions. An example is a numpy array containing the positions and velocities of the pole in CartPole.
> - reward (SupportsFloat) – The reward as a result of taking the action.
> - terminated (bool) – Whether the agent reaches the terminal state (as defined under the MDP of the task) which can be positive or negative. An example is reaching the goal state or moving into the lava from the Sutton and Barton, Gridworld. If true, the user needs to call [reset()](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset).
> - truncated (bool) – Whether the truncation condition outside the scope of the MDP is satisfied. Typically, this is a timelimit, but could also be used to indicate an agent physically going out of bounds. Can be used to end the episode prematurely before a terminal state is reached. If true, the user needs to call [reset()](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset).
> - info (dict) – Contains auxiliary diagnostic information (helpful for debugging, learning, and logging). This might, for instance, contain: metrics that describe the agent’s performance state, variables that are hidden from observations, or individual reward terms that are combined to produce the total reward. In OpenAI Gym <v26, it contains “TimeLimit.truncated” to distinguish truncation and termination, however this is deprecated in favour of returning terminated and truncated variables.

There are two solutions:
1. Keep doing it our way, and if we need to interface it with some existing framework/library (eg. stable-baselines3 for RL), we write and adapter.
2. Do it as specified above by Gym. This requires an API change but I think it's worth it. Concretely, this means:
 - Currently, for the base environment, we are doing `return obs, {}` where the empty dict can be extended to contain arbitrary info.
 - We need to change it to `return obs, 0, False, False, {}`. As before, the user can extend this class to implement different reward/termination criteria if desired.

If we opt for option 2 (which I personally prefer), we should do it ASAP (but perhaps after COBAR) before it becomes even more annoying. What do you think @stimpfli ?

For Isaac Gym I'm definitely going to stick with Gym's specified API above.

**Comment by stimpfli** [comment]
I agree I thing we can implement those changes and merge them as soon as the project ends.
