### ISSUE TITLE
Broken link in the fifth tutorial

### ISSUE THREAD

**Issue by decomiteA** [NeLy-EPFL/flygym#207]
Hello,

Thank you so much for the amazing package, this is a very helpful piece of work!

I think there might be a broken link in the notebook `turning.ipynb` (as well as in the associated [tutorial](https://neuromechfly.org/tutorials/turning.html) on the website). The first link just after the first code cell in the _Implementing the HybridTurningController class_ returns a 404 page not found error.
I think it should be pointing to the `turning_controller.py` file instead as it contains the code mentioned in the tutorial (modulo a slight change in the name of the class). 

A.

**Comment by sibocw** [comment]
Thanks for pointing this out! This is a part of a bigger issue that when we renamed some classes and generally refactored the codebase for the v1.0.0 release, we forgot to update some text blocks in notebooks and the documentation site. I fixed it in the development branch of the upcoming v1.1.0 release and will probably merge it into `main` later today.

(copying @tkclam: FYI)
