### ISSUE TITLE
Breaking API changes in MuJoCo 3.2.3 (Sep 16, 2024)

### ISSUE THREAD

**Issue by stepanove** [NeLy-EPFL/flygym#217]
I just faced this small issue on a fresh installation.
[Breaking API changes](https://mujoco.readthedocs.io/en/latest/changelog.html#id1)

> The runtime options mpr_tolerance and mpr_iterations were renamed to [ccd_tolerance](https://mujoco.readthedocs.io/en/latest/XMLreference.html#option-ccd-tolerance) and [ccd_iterations](https://mujoco.readthedocs.io/en/latest/XMLreference.html#option-ccd-iterations), both in XML and in the [mjOption](https://mujoco.readthedocs.io/en/latest/APIreference/APItypes.html#mjoption) struct. This is because the new convex collision detection pipeline (see below) does not use the MPR algorithm. The semantics of these options remain identical.

**Comment by sibocw** [comment]
Fixed in #218, thank you for pointing this out!

**Comment by sibocw** [comment]
Actually, dm_control version has to be 1.0.23 (not just 1.0.22). 1.0.23 is released only on PyPI. It has not been "released" on their GitHub repo yet. This confused me. I fixed it in eedc04f (directly on the dev branch for the next release here).

Also, I'm fixing the version requirements for MuJoCo and dm_control strictly with == to avoid similar problems in the future. I will just manually update the versions from time to time.
