### ISSUE TITLE
ValueError when `actuated_joints` does not contain all controllable limb joints

### ISSUE THREAD

**Issue by louisgevers** [NeLy-EPFL/flygym#79]
Upon creation of the NeuroMechFly instance, if the `actuated_joints` parameter does not contain all the controllable limb joints (when controlling a subset of joints is desired) a `ValueError` is raised in the line below. This variable seems to only be used for leg adhesion, so wrapping it under a conditional on whether leg adhesion is enabled fixes it, but I believe it should handle the case of unactuated leg joints? Or is there a better way to control a subset of joints?

https://github.com/NeLy-EPFL/flygym/blob/d1556165729a5f947b7abf90eb13725aab7cccf1/flygym/mujoco/core.py#L385-L390

**Comment by sibocw** [comment]
Thanks for the bug report! @stimpfli can you take a look at this please? It seems that it assumes the tarsus is actuated?

**Comment by stimpfli** [comment]
This is related to the automated control of adhesion. Should we remove all code related to it from the main and leave it in a branch for now until I have time to find a better way of controlling that ?

**Comment by sibocw** [comment]
You mean the legacy code where you controlled adhesion on/off based on z position? If so, I agree that it's the best if we remove it.

Could you please either
- do that in a separate branch and create a PR into `develop`, or
- if you don't have time at the moment, please tell Louis here to just by pass it for now?

**Comment by stimpfli** [comment]
#82

**Comment by sibocw** [comment]
Merged — thanks!
